import "server-only";
import { KEY_PREFIX_BY_PURPOSE, type FilePurpose, type StorageVisibility } from "@/lib/media";

/* -------------------------------------------------------------------------- */
/* Storage keys — Phase 18.                                                    */
/*                                                                              */
/* A key is the ONLY thing that addresses an object, so it is built here,       */
/* server-side, from three inputs: the purpose's namespace, an owner-scoped      */
/* folder, and the asset's own random id.                                       */
/*                                                                              */
/* WHAT IS NEVER IN A KEY: the uploaded filename, the teacher's name, their      */
/* phone number, the course title. Object keys leak (logs, CDN metrics, a        */
/* screenshot of a URL in a support ticket), so they carry no personal data.     */
/* -------------------------------------------------------------------------- */

/** Owner scope segment: opaque ids only. */
function scopeSegment(ownerScopeId: string): string {
  // Defensive: an id is generated by `newId`, but a key must be structurally
  // incapable of traversal even if a caller is wrong about that.
  const safe = ownerScopeId.replace(/[^A-Za-z0-9_-]/g, "");
  if (safe.length === 0) throw new Error("storage key scope must not be empty");
  return safe.slice(0, 64);
}

/**
 * Build the key for a new asset.
 *
 *   <visibility>/<purpose-namespace>/<scope>/<assetId>.<ext>
 *
 * Examples:
 *   private/verification/usr-abc123/fa-Xy9….pdf
 *   public/teacher-photos/usr-abc123/fa-Qz1….jpg
 *   public/course-covers/crs-77aa/fa-Lm4….webp
 */
export function buildStorageKey(input: {
  purpose: FilePurpose;
  ownerScopeId: string;
  assetId: string;
  extension: string;
}): string {
  const prefix = KEY_PREFIX_BY_PURPOSE[input.purpose];
  const extension = input.extension.replace(/[^a-z0-9]/gi, "").toLowerCase().slice(0, 8) || "bin";
  return `${prefix}/${scopeSegment(input.ownerScopeId)}/${scopeSegment(input.assetId)}.${extension}`;
}

/** The visibility a key belongs to, derived from its namespace. */
export function visibilityOfKey(key: string): StorageVisibility | null {
  if (key.startsWith("private/")) return "private";
  if (key.startsWith("public/")) return "public";
  return null;
}

/**
 * A key is acceptable only when it is namespaced, has no traversal segments and
 * is plain ASCII. Used before every provider call, so a forged key from a
 * browser can never reach storage.
 */
export function isSafeStorageKey(key: string): boolean {
  if (key.length === 0 || key.length > 512) return false;
  if (key.startsWith("/") || key.includes("..") || key.includes("//")) return false;
  if (key.includes("?") || key.includes("#") || key.includes("\\")) return false;
  if (/[\s\x00-\x1f\x7f]/.test(key)) return false;
  return visibilityOfKey(key) !== null;
}
